repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: yarn-run-pre-commit
        name: yarn lint
        language: system
        entry: yarn pre-commit
        pass_filenames: false
        always_run: true

default_language_version:
  python: python3.8
