compiler:
  solc:
    version: null
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
  vyper:
    version: 0.3.1

networks:
  default: hardhat-fork

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0

dotenv: .env
