compiler:
  solc:
    version: 0.8.9
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
      - "@0xsequence=abdullathedruid/create3@0.0.0/contracts"
  vyper:
    version: 0.3.1

networks:
  default: mainnet-hardhat-fork

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - abdullathedruid/create3@0.0.0

hypothesis:
  max_examples: 10
