compiler:
  solc:
    version: 0.8.9
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
  vyper:
    version: 0.3.1

networks:
  default: mainnet-hardhat-fork

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0

hypothesis:
  max_examples: 10
