name: main

on: [push, pull_request]

env:
  ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}

  # increasing available memory for node reduces issues with ganache crashing
  # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes
  NODE_OPTIONS: --max_old_space_size=4096

  CACHED_COMPILER_PATHS: |
    ~/.solcx
    ~/.vvm

  CACHED_DEPENDENCY_PATHS: |
    ~/.cache/pip

jobs:

  lint_and_tests:
    name: Install Dependencies, run lint and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Cache Compiler Installations
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHED_COMPILER_PATHS }}
          key: ${{ runner.os }}-compiler-cache

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install Ganache
        run: npm install -g ganache-cli@6.12.2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install pre-commit hooks
        run: pre-commit install

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Run Tests
        run: brownie test
